/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptedPapersRouteImport } from './routes/accepted-papers'
import { Route as AdvisoryBoardRouteImport } from './routes/advisory-board'
import { Route as AimsScopeRouteImport } from './routes/aims-scope'
import { Route as ApcRouteImport } from './routes/apc'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AssociateEditorsRouteImport } from './routes/associate-editors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthorDeclarationFormRouteImport } from './routes/author-declaration-form'
import { Route as AuthorGuidelinesRouteImport } from './routes/author-guidelines'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CopernicusRouteImport } from './routes/copernicus'
import { Route as CopyrightFormRouteImport } from './routes/copyright-form'
import { Route as CopyrightLicenseRouteImport } from './routes/copyright-license'
import { Route as CopyrightPolicyRouteImport } from './routes/copyright-policy'
import { Route as CrossrefRouteImport } from './routes/crossref'
import { Route as CurrentIssueRouteImport } from './routes/current-issue'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DoiInformationRouteImport } from './routes/doi-information'
import { Route as EbooksRouteImport } from './routes/ebooks'
import { Route as EditorInChiefRouteImport } from './routes/editor-in-chief'
import { Route as EditorialBoardRouteImport } from './routes/editorial-board'
import { Route as EditorialOfficeRouteImport } from './routes/editorial-office'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GoogleScholarRouteImport } from './routes/google-scholar'
import { Route as InPressRouteImport } from './routes/in-press'
import { Route as IndexingRouteImport } from './routes/indexing'
import { Route as JoinReviewerRouteImport } from './routes/join-reviewer'
import { Route as LatestArticlesRouteImport } from './routes/latest-articles'
import { Route as ManuscriptTemplateRouteImport } from './routes/manuscript-template'
import { Route as MostCitedRouteImport } from './routes/most-cited'
import { Route as MostViewedRouteImport } from './routes/most-viewed'
import { Route as OpenAccessPolicyRouteImport } from './routes/open-access-policy'
import { Route as PeerReviewPolicyRouteImport } from './routes/peer-review-policy'
import { Route as PlagiarismPolicyRouteImport } from './routes/plagiarism-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PublicationEthicsRouteImport } from './routes/publication-ethics'
import { Route as PublicationProcessRouteImport } from './routes/publication-process'
import { Route as PublicationTimelineRouteImport } from './routes/publication-timeline'
import { Route as ReviewersRouteImport } from './routes/reviewers'
import { Route as RoadRouteImport } from './routes/road'
import { Route as SpecialIssuesRouteImport } from './routes/special-issues'
import { Route as SubmissionGuidelinesRouteImport } from './routes/submission-guidelines'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SubmitQueryRouteImport } from './routes/submit-query'
import { Route as TechnicalSupportRouteImport } from './routes/technical-support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSuperAdminRouteRouteImport } from './routes/_authenticated/super-admin/route'
import { Route as ArchivesIssueRouteImport } from './routes/archives.issue'
import { Route as ArchivesVolumeRouteImport } from './routes/archives.volume'
import { Route as ArchivesYearRouteImport } from './routes/archives.year'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ConferencesCallForPapersRouteImport } from './routes/conferences.call-for-papers'
import { Route as ConferencesPastRouteImport } from './routes/conferences.past'
import { Route as ConferencesProceedingsRouteImport } from './routes/conferences.proceedings'
import { Route as EbooksDownloadRouteImport } from './routes/ebooks.download'
import { Route as EbooksSubmitRouteImport } from './routes/ebooks.submit'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAdvertisementsRouteImport } from './routes/_authenticated/admin/advertisements'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin/articles'
import { Route as AuthenticatedAdminBoardRouteImport } from './routes/_authenticated/admin/board'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin/certificates'
import { Route as AuthenticatedAdminConferencesRouteImport } from './routes/_authenticated/admin/conferences'
import { Route as AuthenticatedAdminDoiRouteImport } from './routes/_authenticated/admin/doi'
import { Route as AuthenticatedAdminEbooksRouteImport } from './routes/_authenticated/admin/ebooks'
import { Route as AuthenticatedAdminImpactFactorRouteImport } from './routes/_authenticated/admin/impact-factor'
import { Route as AuthenticatedAdminIssuesRouteImport } from './routes/_authenticated/admin/issues'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin/maintenance'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin/submissions'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin/subscribers'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedSuperAdminAdvisoryBoardRouteImport } from './routes/_authenticated/super-admin/advisory-board'
import { Route as AuthenticatedSuperAdminAnalyticsRouteImport } from './routes/_authenticated/super-admin/analytics'
import { Route as AuthenticatedSuperAdminAnimationsRouteImport } from './routes/_authenticated/super-admin/animations'
import { Route as AuthenticatedSuperAdminAnnouncementsRouteImport } from './routes/_authenticated/super-admin/announcements'
import { Route as AuthenticatedSuperAdminApiKeysRouteImport } from './routes/_authenticated/super-admin/api-keys'
import { Route as AuthenticatedSuperAdminCertificatesRouteImport } from './routes/_authenticated/super-admin/certificates'
import { Route as AuthenticatedSuperAdminChiefPatronsRouteImport } from './routes/_authenticated/super-admin/chief-patrons'
import { Route as AuthenticatedSuperAdminConferencesRouteImport } from './routes/_authenticated/super-admin/conferences'
import { Route as AuthenticatedSuperAdminDashboardRouteImport } from './routes/_authenticated/super-admin/dashboard'
import { Route as AuthenticatedSuperAdminDeploymentRouteImport } from './routes/_authenticated/super-admin/deployment'
import { Route as AuthenticatedSuperAdminEbooksRouteImport } from './routes/_authenticated/super-admin/ebooks'
import { Route as AuthenticatedSuperAdminEditorialBoardRouteImport } from './routes/_authenticated/super-admin/editorial-board'
import { Route as AuthenticatedSuperAdminFeesRouteImport } from './routes/_authenticated/super-admin/fees'
import { Route as AuthenticatedSuperAdminImpactFactorsRouteImport } from './routes/_authenticated/super-admin/impact-factors'
import { Route as AuthenticatedSuperAdminIssuesRouteImport } from './routes/_authenticated/super-admin/issues'
import { Route as AuthenticatedSuperAdminPapersRouteImport } from './routes/_authenticated/super-admin/papers'
import { Route as AuthenticatedSuperAdminReviewerBoardRouteImport } from './routes/_authenticated/super-admin/reviewer-board'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin/settings'
import { Route as AuthenticatedSuperAdminSitesRouteImport } from './routes/_authenticated/super-admin/sites'
import { Route as AuthenticatedSuperAdminTeamMembersRouteImport } from './routes/_authenticated/super-admin/team-members'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated/super-admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptedPapersRoute = AcceptedPapersRouteImport.update({
  id: '/accepted-papers',
  path: '/accepted-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryBoardRoute = AdvisoryBoardRouteImport.update({
  id: '/advisory-board',
  path: '/advisory-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AimsScopeRoute = AimsScopeRouteImport.update({
  id: '/aims-scope',
  path: '/aims-scope',
  getParentRoute: () => rootRouteImport,
} as any)
const ApcRoute = ApcRouteImport.update({
  id: '/apc',
  path: '/apc',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociateEditorsRoute = AssociateEditorsRouteImport.update({
  id: '/associate-editors',
  path: '/associate-editors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorDeclarationFormRoute = AuthorDeclarationFormRouteImport.update({
  id: '/author-declaration-form',
  path: '/author-declaration-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorGuidelinesRoute = AuthorGuidelinesRouteImport.update({
  id: '/author-guidelines',
  path: '/author-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CopernicusRoute = CopernicusRouteImport.update({
  id: '/copernicus',
  path: '/copernicus',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightFormRoute = CopyrightFormRouteImport.update({
  id: '/copyright-form',
  path: '/copyright-form',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightLicenseRoute = CopyrightLicenseRouteImport.update({
  id: '/copyright-license',
  path: '/copyright-license',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightPolicyRoute = CopyrightPolicyRouteImport.update({
  id: '/copyright-policy',
  path: '/copyright-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossrefRoute = CrossrefRouteImport.update({
  id: '/crossref',
  path: '/crossref',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentIssueRoute = CurrentIssueRouteImport.update({
  id: '/current-issue',
  path: '/current-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DoiInformationRoute = DoiInformationRouteImport.update({
  id: '/doi-information',
  path: '/doi-information',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksRoute = EbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorInChiefRoute = EditorInChiefRouteImport.update({
  id: '/editor-in-chief',
  path: '/editor-in-chief',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialBoardRoute = EditorialBoardRouteImport.update({
  id: '/editorial-board',
  path: '/editorial-board',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialOfficeRoute = EditorialOfficeRouteImport.update({
  id: '/editorial-office',
  path: '/editorial-office',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleScholarRoute = GoogleScholarRouteImport.update({
  id: '/google-scholar',
  path: '/google-scholar',
  getParentRoute: () => rootRouteImport,
} as any)
const InPressRoute = InPressRouteImport.update({
  id: '/in-press',
  path: '/in-press',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexingRoute = IndexingRouteImport.update({
  id: '/indexing',
  path: '/indexing',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinReviewerRoute = JoinReviewerRouteImport.update({
  id: '/join-reviewer',
  path: '/join-reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestArticlesRoute = LatestArticlesRouteImport.update({
  id: '/latest-articles',
  path: '/latest-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuscriptTemplateRoute = ManuscriptTemplateRouteImport.update({
  id: '/manuscript-template',
  path: '/manuscript-template',
  getParentRoute: () => rootRouteImport,
} as any)
const MostCitedRoute = MostCitedRouteImport.update({
  id: '/most-cited',
  path: '/most-cited',
  getParentRoute: () => rootRouteImport,
} as any)
const MostViewedRoute = MostViewedRouteImport.update({
  id: '/most-viewed',
  path: '/most-viewed',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenAccessPolicyRoute = OpenAccessPolicyRouteImport.update({
  id: '/open-access-policy',
  path: '/open-access-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PeerReviewPolicyRoute = PeerReviewPolicyRouteImport.update({
  id: '/peer-review-policy',
  path: '/peer-review-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlagiarismPolicyRoute = PlagiarismPolicyRouteImport.update({
  id: '/plagiarism-policy',
  path: '/plagiarism-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationEthicsRoute = PublicationEthicsRouteImport.update({
  id: '/publication-ethics',
  path: '/publication-ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationProcessRoute = PublicationProcessRouteImport.update({
  id: '/publication-process',
  path: '/publication-process',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationTimelineRoute = PublicationTimelineRouteImport.update({
  id: '/publication-timeline',
  path: '/publication-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewersRoute = ReviewersRouteImport.update({
  id: '/reviewers',
  path: '/reviewers',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadRoute = RoadRouteImport.update({
  id: '/road',
  path: '/road',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialIssuesRoute = SpecialIssuesRouteImport.update({
  id: '/special-issues',
  path: '/special-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionGuidelinesRoute = SubmissionGuidelinesRouteImport.update({
  id: '/submission-guidelines',
  path: '/submission-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitQueryRoute = SubmitQueryRouteImport.update({
  id: '/submit-query',
  path: '/submit-query',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalSupportRoute = TechnicalSupportRouteImport.update({
  id: '/technical-support',
  path: '/technical-support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRouteRoute =
  AuthenticatedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ArchivesIssueRoute = ArchivesIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => ArchivesRoute,
} as any)
const ArchivesVolumeRoute = ArchivesVolumeRouteImport.update({
  id: '/volume',
  path: '/volume',
  getParentRoute: () => ArchivesRoute,
} as any)
const ArchivesYearRoute = ArchivesYearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => ArchivesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ConferencesCallForPapersRoute =
  ConferencesCallForPapersRouteImport.update({
    id: '/call-for-papers',
    path: '/call-for-papers',
    getParentRoute: () => ConferencesRoute,
  } as any)
const ConferencesPastRoute = ConferencesPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => ConferencesRoute,
} as any)
const ConferencesProceedingsRoute = ConferencesProceedingsRouteImport.update({
  id: '/proceedings',
  path: '/proceedings',
  getParentRoute: () => ConferencesRoute,
} as any)
const EbooksDownloadRoute = EbooksDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => EbooksRoute,
} as any)
const EbooksSubmitRoute = EbooksSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => EbooksRoute,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdvertisementsRoute =
  AuthenticatedAdminAdvertisementsRouteImport.update({
    id: '/advertisements',
    path: '/advertisements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBoardRoute = AuthenticatedAdminBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConferencesRoute =
  AuthenticatedAdminConferencesRouteImport.update({
    id: '/conferences',
    path: '/conferences',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDoiRoute = AuthenticatedAdminDoiRouteImport.update({
  id: '/doi',
  path: '/doi',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEbooksRoute =
  AuthenticatedAdminEbooksRouteImport.update({
    id: '/ebooks',
    path: '/ebooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImpactFactorRoute =
  AuthenticatedAdminImpactFactorRouteImport.update({
    id: '/impact-factor',
    path: '/impact-factor',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIssuesRoute =
  AuthenticatedAdminIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminAdvisoryBoardRoute =
  AuthenticatedSuperAdminAdvisoryBoardRouteImport.update({
    id: '/advisory-board',
    path: '/advisory-board',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminAnalyticsRoute =
  AuthenticatedSuperAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminAnimationsRoute =
  AuthenticatedSuperAdminAnimationsRouteImport.update({
    id: '/animations',
    path: '/animations',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminAnnouncementsRoute =
  AuthenticatedSuperAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminApiKeysRoute =
  AuthenticatedSuperAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminCertificatesRoute =
  AuthenticatedSuperAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminChiefPatronsRoute =
  AuthenticatedSuperAdminChiefPatronsRouteImport.update({
    id: '/chief-patrons',
    path: '/chief-patrons',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminConferencesRoute =
  AuthenticatedSuperAdminConferencesRouteImport.update({
    id: '/conferences',
    path: '/conferences',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminDashboardRoute =
  AuthenticatedSuperAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminDeploymentRoute =
  AuthenticatedSuperAdminDeploymentRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminEbooksRoute =
  AuthenticatedSuperAdminEbooksRouteImport.update({
    id: '/ebooks',
    path: '/ebooks',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminEditorialBoardRoute =
  AuthenticatedSuperAdminEditorialBoardRouteImport.update({
    id: '/editorial-board',
    path: '/editorial-board',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminFeesRoute =
  AuthenticatedSuperAdminFeesRouteImport.update({
    id: '/fees',
    path: '/fees',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminImpactFactorsRoute =
  AuthenticatedSuperAdminImpactFactorsRouteImport.update({
    id: '/impact-factors',
    path: '/impact-factors',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminIssuesRoute =
  AuthenticatedSuperAdminIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminPapersRoute =
  AuthenticatedSuperAdminPapersRouteImport.update({
    id: '/papers',
    path: '/papers',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminReviewerBoardRoute =
  AuthenticatedSuperAdminReviewerBoardRouteImport.update({
    id: '/reviewer-board',
    path: '/reviewer-board',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminSitesRoute =
  AuthenticatedSuperAdminSitesRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminTeamMembersRoute =
  AuthenticatedSuperAdminTeamMembersRouteImport.update({
    id: '/team-members',
    path: '/team-members',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accepted-papers': typeof AcceptedPapersRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/aims-scope': typeof AimsScopeRoute
  '/apc': typeof ApcRoute
  '/archives': typeof ArchivesRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/associate-editors': typeof AssociateEditorsRoute
  '/auth': typeof AuthRoute
  '/author-declaration-form': typeof AuthorDeclarationFormRoute
  '/author-guidelines': typeof AuthorGuidelinesRoute
  '/conferences': typeof ConferencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/copernicus': typeof CopernicusRoute
  '/copyright-form': typeof CopyrightFormRoute
  '/copyright-license': typeof CopyrightLicenseRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/crossref': typeof CrossrefRoute
  '/current-issue': typeof CurrentIssueRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doi-information': typeof DoiInformationRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/editor-in-chief': typeof EditorInChiefRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/editorial-office': typeof EditorialOfficeRoute
  '/faqs': typeof FaqsRoute
  '/google-scholar': typeof GoogleScholarRoute
  '/in-press': typeof InPressRoute
  '/indexing': typeof IndexingRoute
  '/join-reviewer': typeof JoinReviewerRoute
  '/latest-articles': typeof LatestArticlesRoute
  '/manuscript-template': typeof ManuscriptTemplateRoute
  '/most-cited': typeof MostCitedRoute
  '/most-viewed': typeof MostViewedRoute
  '/open-access-policy': typeof OpenAccessPolicyRoute
  '/peer-review-policy': typeof PeerReviewPolicyRoute
  '/plagiarism-policy': typeof PlagiarismPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/publication-ethics': typeof PublicationEthicsRoute
  '/publication-process': typeof PublicationProcessRoute
  '/publication-timeline': typeof PublicationTimelineRoute
  '/reviewers': typeof ReviewersRoute
  '/road': typeof RoadRoute
  '/special-issues': typeof SpecialIssuesRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/submit': typeof SubmitRoute
  '/submit-query': typeof SubmitQueryRoute
  '/technical-support': typeof TechnicalSupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/vision-mission': typeof VisionMissionRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/archives/issue': typeof ArchivesIssueRoute
  '/archives/volume': typeof ArchivesVolumeRoute
  '/archives/year': typeof ArchivesYearRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/conferences/call-for-papers': typeof ConferencesCallForPapersRoute
  '/conferences/past': typeof ConferencesPastRoute
  '/conferences/proceedings': typeof ConferencesProceedingsRoute
  '/ebooks/download': typeof EbooksDownloadRoute
  '/ebooks/submit': typeof EbooksSubmitRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/admin/advertisements': typeof AuthenticatedAdminAdvertisementsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/board': typeof AuthenticatedAdminBoardRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/conferences': typeof AuthenticatedAdminConferencesRoute
  '/admin/doi': typeof AuthenticatedAdminDoiRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/impact-factor': typeof AuthenticatedAdminImpactFactorRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/super-admin/advisory-board': typeof AuthenticatedSuperAdminAdvisoryBoardRoute
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/animations': typeof AuthenticatedSuperAdminAnimationsRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/api-keys': typeof AuthenticatedSuperAdminApiKeysRoute
  '/super-admin/certificates': typeof AuthenticatedSuperAdminCertificatesRoute
  '/super-admin/chief-patrons': typeof AuthenticatedSuperAdminChiefPatronsRoute
  '/super-admin/conferences': typeof AuthenticatedSuperAdminConferencesRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/super-admin/deployment': typeof AuthenticatedSuperAdminDeploymentRoute
  '/super-admin/ebooks': typeof AuthenticatedSuperAdminEbooksRoute
  '/super-admin/editorial-board': typeof AuthenticatedSuperAdminEditorialBoardRoute
  '/super-admin/fees': typeof AuthenticatedSuperAdminFeesRoute
  '/super-admin/impact-factors': typeof AuthenticatedSuperAdminImpactFactorsRoute
  '/super-admin/issues': typeof AuthenticatedSuperAdminIssuesRoute
  '/super-admin/papers': typeof AuthenticatedSuperAdminPapersRoute
  '/super-admin/reviewer-board': typeof AuthenticatedSuperAdminReviewerBoardRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/sites': typeof AuthenticatedSuperAdminSitesRoute
  '/super-admin/team-members': typeof AuthenticatedSuperAdminTeamMembersRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accepted-papers': typeof AcceptedPapersRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/aims-scope': typeof AimsScopeRoute
  '/apc': typeof ApcRoute
  '/archives': typeof ArchivesRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/associate-editors': typeof AssociateEditorsRoute
  '/auth': typeof AuthRoute
  '/author-declaration-form': typeof AuthorDeclarationFormRoute
  '/author-guidelines': typeof AuthorGuidelinesRoute
  '/conferences': typeof ConferencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/copernicus': typeof CopernicusRoute
  '/copyright-form': typeof CopyrightFormRoute
  '/copyright-license': typeof CopyrightLicenseRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/crossref': typeof CrossrefRoute
  '/current-issue': typeof CurrentIssueRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doi-information': typeof DoiInformationRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/editor-in-chief': typeof EditorInChiefRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/editorial-office': typeof EditorialOfficeRoute
  '/faqs': typeof FaqsRoute
  '/google-scholar': typeof GoogleScholarRoute
  '/in-press': typeof InPressRoute
  '/indexing': typeof IndexingRoute
  '/join-reviewer': typeof JoinReviewerRoute
  '/latest-articles': typeof LatestArticlesRoute
  '/manuscript-template': typeof ManuscriptTemplateRoute
  '/most-cited': typeof MostCitedRoute
  '/most-viewed': typeof MostViewedRoute
  '/open-access-policy': typeof OpenAccessPolicyRoute
  '/peer-review-policy': typeof PeerReviewPolicyRoute
  '/plagiarism-policy': typeof PlagiarismPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/publication-ethics': typeof PublicationEthicsRoute
  '/publication-process': typeof PublicationProcessRoute
  '/publication-timeline': typeof PublicationTimelineRoute
  '/reviewers': typeof ReviewersRoute
  '/road': typeof RoadRoute
  '/special-issues': typeof SpecialIssuesRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/submit': typeof SubmitRoute
  '/submit-query': typeof SubmitQueryRoute
  '/technical-support': typeof TechnicalSupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/vision-mission': typeof VisionMissionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/archives/issue': typeof ArchivesIssueRoute
  '/archives/volume': typeof ArchivesVolumeRoute
  '/archives/year': typeof ArchivesYearRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/conferences/call-for-papers': typeof ConferencesCallForPapersRoute
  '/conferences/past': typeof ConferencesPastRoute
  '/conferences/proceedings': typeof ConferencesProceedingsRoute
  '/ebooks/download': typeof EbooksDownloadRoute
  '/ebooks/submit': typeof EbooksSubmitRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/admin/advertisements': typeof AuthenticatedAdminAdvertisementsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/board': typeof AuthenticatedAdminBoardRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/conferences': typeof AuthenticatedAdminConferencesRoute
  '/admin/doi': typeof AuthenticatedAdminDoiRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/impact-factor': typeof AuthenticatedAdminImpactFactorRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/super-admin/advisory-board': typeof AuthenticatedSuperAdminAdvisoryBoardRoute
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/animations': typeof AuthenticatedSuperAdminAnimationsRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/api-keys': typeof AuthenticatedSuperAdminApiKeysRoute
  '/super-admin/certificates': typeof AuthenticatedSuperAdminCertificatesRoute
  '/super-admin/chief-patrons': typeof AuthenticatedSuperAdminChiefPatronsRoute
  '/super-admin/conferences': typeof AuthenticatedSuperAdminConferencesRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/super-admin/deployment': typeof AuthenticatedSuperAdminDeploymentRoute
  '/super-admin/ebooks': typeof AuthenticatedSuperAdminEbooksRoute
  '/super-admin/editorial-board': typeof AuthenticatedSuperAdminEditorialBoardRoute
  '/super-admin/fees': typeof AuthenticatedSuperAdminFeesRoute
  '/super-admin/impact-factors': typeof AuthenticatedSuperAdminImpactFactorsRoute
  '/super-admin/issues': typeof AuthenticatedSuperAdminIssuesRoute
  '/super-admin/papers': typeof AuthenticatedSuperAdminPapersRoute
  '/super-admin/reviewer-board': typeof AuthenticatedSuperAdminReviewerBoardRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/sites': typeof AuthenticatedSuperAdminSitesRoute
  '/super-admin/team-members': typeof AuthenticatedSuperAdminTeamMembersRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accepted-papers': typeof AcceptedPapersRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/aims-scope': typeof AimsScopeRoute
  '/apc': typeof ApcRoute
  '/archives': typeof ArchivesRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/associate-editors': typeof AssociateEditorsRoute
  '/auth': typeof AuthRoute
  '/author-declaration-form': typeof AuthorDeclarationFormRoute
  '/author-guidelines': typeof AuthorGuidelinesRoute
  '/conferences': typeof ConferencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/copernicus': typeof CopernicusRoute
  '/copyright-form': typeof CopyrightFormRoute
  '/copyright-license': typeof CopyrightLicenseRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/crossref': typeof CrossrefRoute
  '/current-issue': typeof CurrentIssueRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doi-information': typeof DoiInformationRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/editor-in-chief': typeof EditorInChiefRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/editorial-office': typeof EditorialOfficeRoute
  '/faqs': typeof FaqsRoute
  '/google-scholar': typeof GoogleScholarRoute
  '/in-press': typeof InPressRoute
  '/indexing': typeof IndexingRoute
  '/join-reviewer': typeof JoinReviewerRoute
  '/latest-articles': typeof LatestArticlesRoute
  '/manuscript-template': typeof ManuscriptTemplateRoute
  '/most-cited': typeof MostCitedRoute
  '/most-viewed': typeof MostViewedRoute
  '/open-access-policy': typeof OpenAccessPolicyRoute
  '/peer-review-policy': typeof PeerReviewPolicyRoute
  '/plagiarism-policy': typeof PlagiarismPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/publication-ethics': typeof PublicationEthicsRoute
  '/publication-process': typeof PublicationProcessRoute
  '/publication-timeline': typeof PublicationTimelineRoute
  '/reviewers': typeof ReviewersRoute
  '/road': typeof RoadRoute
  '/special-issues': typeof SpecialIssuesRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/submit': typeof SubmitRoute
  '/submit-query': typeof SubmitQueryRoute
  '/technical-support': typeof TechnicalSupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/vision-mission': typeof VisionMissionRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/archives/issue': typeof ArchivesIssueRoute
  '/archives/volume': typeof ArchivesVolumeRoute
  '/archives/year': typeof ArchivesYearRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/conferences/call-for-papers': typeof ConferencesCallForPapersRoute
  '/conferences/past': typeof ConferencesPastRoute
  '/conferences/proceedings': typeof ConferencesProceedingsRoute
  '/ebooks/download': typeof EbooksDownloadRoute
  '/ebooks/submit': typeof EbooksSubmitRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/_authenticated/admin/advertisements': typeof AuthenticatedAdminAdvertisementsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/board': typeof AuthenticatedAdminBoardRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/conferences': typeof AuthenticatedAdminConferencesRoute
  '/_authenticated/admin/doi': typeof AuthenticatedAdminDoiRoute
  '/_authenticated/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/_authenticated/admin/impact-factor': typeof AuthenticatedAdminImpactFactorRoute
  '/_authenticated/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/super-admin/advisory-board': typeof AuthenticatedSuperAdminAdvisoryBoardRoute
  '/_authenticated/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/_authenticated/super-admin/animations': typeof AuthenticatedSuperAdminAnimationsRoute
  '/_authenticated/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/_authenticated/super-admin/api-keys': typeof AuthenticatedSuperAdminApiKeysRoute
  '/_authenticated/super-admin/certificates': typeof AuthenticatedSuperAdminCertificatesRoute
  '/_authenticated/super-admin/chief-patrons': typeof AuthenticatedSuperAdminChiefPatronsRoute
  '/_authenticated/super-admin/conferences': typeof AuthenticatedSuperAdminConferencesRoute
  '/_authenticated/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/_authenticated/super-admin/deployment': typeof AuthenticatedSuperAdminDeploymentRoute
  '/_authenticated/super-admin/ebooks': typeof AuthenticatedSuperAdminEbooksRoute
  '/_authenticated/super-admin/editorial-board': typeof AuthenticatedSuperAdminEditorialBoardRoute
  '/_authenticated/super-admin/fees': typeof AuthenticatedSuperAdminFeesRoute
  '/_authenticated/super-admin/impact-factors': typeof AuthenticatedSuperAdminImpactFactorsRoute
  '/_authenticated/super-admin/issues': typeof AuthenticatedSuperAdminIssuesRoute
  '/_authenticated/super-admin/papers': typeof AuthenticatedSuperAdminPapersRoute
  '/_authenticated/super-admin/reviewer-board': typeof AuthenticatedSuperAdminReviewerBoardRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/sites': typeof AuthenticatedSuperAdminSitesRoute
  '/_authenticated/super-admin/team-members': typeof AuthenticatedSuperAdminTeamMembersRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accepted-papers'
    | '/advisory-board'
    | '/aims-scope'
    | '/apc'
    | '/archives'
    | '/articles'
    | '/associate-editors'
    | '/auth'
    | '/author-declaration-form'
    | '/author-guidelines'
    | '/conferences'
    | '/contact'
    | '/copernicus'
    | '/copyright-form'
    | '/copyright-license'
    | '/copyright-policy'
    | '/crossref'
    | '/current-issue'
    | '/disclaimer'
    | '/doi-information'
    | '/ebooks'
    | '/editor-in-chief'
    | '/editorial-board'
    | '/editorial-office'
    | '/faqs'
    | '/google-scholar'
    | '/in-press'
    | '/indexing'
    | '/join-reviewer'
    | '/latest-articles'
    | '/manuscript-template'
    | '/most-cited'
    | '/most-viewed'
    | '/open-access-policy'
    | '/peer-review-policy'
    | '/plagiarism-policy'
    | '/privacy'
    | '/publication-ethics'
    | '/publication-process'
    | '/publication-timeline'
    | '/reviewers'
    | '/road'
    | '/special-issues'
    | '/submission-guidelines'
    | '/submit'
    | '/submit-query'
    | '/technical-support'
    | '/terms'
    | '/verify'
    | '/vision-mission'
    | '/super-admin'
    | '/admin'
    | '/dashboard'
    | '/archives/issue'
    | '/archives/volume'
    | '/archives/year'
    | '/articles/$slug'
    | '/conferences/call-for-papers'
    | '/conferences/past'
    | '/conferences/proceedings'
    | '/ebooks/download'
    | '/ebooks/submit'
    | '/super-admin/login'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/articles'
    | '/admin/board'
    | '/admin/certificates'
    | '/admin/conferences'
    | '/admin/doi'
    | '/admin/ebooks'
    | '/admin/impact-factor'
    | '/admin/issues'
    | '/admin/maintenance'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin/users'
    | '/super-admin/advisory-board'
    | '/super-admin/analytics'
    | '/super-admin/animations'
    | '/super-admin/announcements'
    | '/super-admin/api-keys'
    | '/super-admin/certificates'
    | '/super-admin/chief-patrons'
    | '/super-admin/conferences'
    | '/super-admin/dashboard'
    | '/super-admin/deployment'
    | '/super-admin/ebooks'
    | '/super-admin/editorial-board'
    | '/super-admin/fees'
    | '/super-admin/impact-factors'
    | '/super-admin/issues'
    | '/super-admin/papers'
    | '/super-admin/reviewer-board'
    | '/super-admin/settings'
    | '/super-admin/sites'
    | '/super-admin/team-members'
    | '/super-admin/users'
    | '/admin/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accepted-papers'
    | '/advisory-board'
    | '/aims-scope'
    | '/apc'
    | '/archives'
    | '/articles'
    | '/associate-editors'
    | '/auth'
    | '/author-declaration-form'
    | '/author-guidelines'
    | '/conferences'
    | '/contact'
    | '/copernicus'
    | '/copyright-form'
    | '/copyright-license'
    | '/copyright-policy'
    | '/crossref'
    | '/current-issue'
    | '/disclaimer'
    | '/doi-information'
    | '/ebooks'
    | '/editor-in-chief'
    | '/editorial-board'
    | '/editorial-office'
    | '/faqs'
    | '/google-scholar'
    | '/in-press'
    | '/indexing'
    | '/join-reviewer'
    | '/latest-articles'
    | '/manuscript-template'
    | '/most-cited'
    | '/most-viewed'
    | '/open-access-policy'
    | '/peer-review-policy'
    | '/plagiarism-policy'
    | '/privacy'
    | '/publication-ethics'
    | '/publication-process'
    | '/publication-timeline'
    | '/reviewers'
    | '/road'
    | '/special-issues'
    | '/submission-guidelines'
    | '/submit'
    | '/submit-query'
    | '/technical-support'
    | '/terms'
    | '/verify'
    | '/vision-mission'
    | '/dashboard'
    | '/archives/issue'
    | '/archives/volume'
    | '/archives/year'
    | '/articles/$slug'
    | '/conferences/call-for-papers'
    | '/conferences/past'
    | '/conferences/proceedings'
    | '/ebooks/download'
    | '/ebooks/submit'
    | '/super-admin/login'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/articles'
    | '/admin/board'
    | '/admin/certificates'
    | '/admin/conferences'
    | '/admin/doi'
    | '/admin/ebooks'
    | '/admin/impact-factor'
    | '/admin/issues'
    | '/admin/maintenance'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin/users'
    | '/super-admin/advisory-board'
    | '/super-admin/analytics'
    | '/super-admin/animations'
    | '/super-admin/announcements'
    | '/super-admin/api-keys'
    | '/super-admin/certificates'
    | '/super-admin/chief-patrons'
    | '/super-admin/conferences'
    | '/super-admin/dashboard'
    | '/super-admin/deployment'
    | '/super-admin/ebooks'
    | '/super-admin/editorial-board'
    | '/super-admin/fees'
    | '/super-admin/impact-factors'
    | '/super-admin/issues'
    | '/super-admin/papers'
    | '/super-admin/reviewer-board'
    | '/super-admin/settings'
    | '/super-admin/sites'
    | '/super-admin/team-members'
    | '/super-admin/users'
    | '/admin'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accepted-papers'
    | '/advisory-board'
    | '/aims-scope'
    | '/apc'
    | '/archives'
    | '/articles'
    | '/associate-editors'
    | '/auth'
    | '/author-declaration-form'
    | '/author-guidelines'
    | '/conferences'
    | '/contact'
    | '/copernicus'
    | '/copyright-form'
    | '/copyright-license'
    | '/copyright-policy'
    | '/crossref'
    | '/current-issue'
    | '/disclaimer'
    | '/doi-information'
    | '/ebooks'
    | '/editor-in-chief'
    | '/editorial-board'
    | '/editorial-office'
    | '/faqs'
    | '/google-scholar'
    | '/in-press'
    | '/indexing'
    | '/join-reviewer'
    | '/latest-articles'
    | '/manuscript-template'
    | '/most-cited'
    | '/most-viewed'
    | '/open-access-policy'
    | '/peer-review-policy'
    | '/plagiarism-policy'
    | '/privacy'
    | '/publication-ethics'
    | '/publication-process'
    | '/publication-timeline'
    | '/reviewers'
    | '/road'
    | '/special-issues'
    | '/submission-guidelines'
    | '/submit'
    | '/submit-query'
    | '/technical-support'
    | '/terms'
    | '/verify'
    | '/vision-mission'
    | '/_authenticated/super-admin'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/archives/issue'
    | '/archives/volume'
    | '/archives/year'
    | '/articles/$slug'
    | '/conferences/call-for-papers'
    | '/conferences/past'
    | '/conferences/proceedings'
    | '/ebooks/download'
    | '/ebooks/submit'
    | '/super-admin/login'
    | '/_authenticated/admin/advertisements'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/board'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/conferences'
    | '/_authenticated/admin/doi'
    | '/_authenticated/admin/ebooks'
    | '/_authenticated/admin/impact-factor'
    | '/_authenticated/admin/issues'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/users'
    | '/_authenticated/super-admin/advisory-board'
    | '/_authenticated/super-admin/analytics'
    | '/_authenticated/super-admin/animations'
    | '/_authenticated/super-admin/announcements'
    | '/_authenticated/super-admin/api-keys'
    | '/_authenticated/super-admin/certificates'
    | '/_authenticated/super-admin/chief-patrons'
    | '/_authenticated/super-admin/conferences'
    | '/_authenticated/super-admin/dashboard'
    | '/_authenticated/super-admin/deployment'
    | '/_authenticated/super-admin/ebooks'
    | '/_authenticated/super-admin/editorial-board'
    | '/_authenticated/super-admin/fees'
    | '/_authenticated/super-admin/impact-factors'
    | '/_authenticated/super-admin/issues'
    | '/_authenticated/super-admin/papers'
    | '/_authenticated/super-admin/reviewer-board'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/sites'
    | '/_authenticated/super-admin/team-members'
    | '/_authenticated/super-admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptedPapersRoute: typeof AcceptedPapersRoute
  AdvisoryBoardRoute: typeof AdvisoryBoardRoute
  AimsScopeRoute: typeof AimsScopeRoute
  ApcRoute: typeof ApcRoute
  ArchivesRoute: typeof ArchivesRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AssociateEditorsRoute: typeof AssociateEditorsRoute
  AuthRoute: typeof AuthRoute
  AuthorDeclarationFormRoute: typeof AuthorDeclarationFormRoute
  AuthorGuidelinesRoute: typeof AuthorGuidelinesRoute
  ConferencesRoute: typeof ConferencesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CopernicusRoute: typeof CopernicusRoute
  CopyrightFormRoute: typeof CopyrightFormRoute
  CopyrightLicenseRoute: typeof CopyrightLicenseRoute
  CopyrightPolicyRoute: typeof CopyrightPolicyRoute
  CrossrefRoute: typeof CrossrefRoute
  CurrentIssueRoute: typeof CurrentIssueRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DoiInformationRoute: typeof DoiInformationRoute
  EbooksRoute: typeof EbooksRouteWithChildren
  EditorInChiefRoute: typeof EditorInChiefRoute
  EditorialBoardRoute: typeof EditorialBoardRoute
  EditorialOfficeRoute: typeof EditorialOfficeRoute
  FaqsRoute: typeof FaqsRoute
  GoogleScholarRoute: typeof GoogleScholarRoute
  InPressRoute: typeof InPressRoute
  IndexingRoute: typeof IndexingRoute
  JoinReviewerRoute: typeof JoinReviewerRoute
  LatestArticlesRoute: typeof LatestArticlesRoute
  ManuscriptTemplateRoute: typeof ManuscriptTemplateRoute
  MostCitedRoute: typeof MostCitedRoute
  MostViewedRoute: typeof MostViewedRoute
  OpenAccessPolicyRoute: typeof OpenAccessPolicyRoute
  PeerReviewPolicyRoute: typeof PeerReviewPolicyRoute
  PlagiarismPolicyRoute: typeof PlagiarismPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicationEthicsRoute: typeof PublicationEthicsRoute
  PublicationProcessRoute: typeof PublicationProcessRoute
  PublicationTimelineRoute: typeof PublicationTimelineRoute
  ReviewersRoute: typeof ReviewersRoute
  RoadRoute: typeof RoadRoute
  SpecialIssuesRoute: typeof SpecialIssuesRoute
  SubmissionGuidelinesRoute: typeof SubmissionGuidelinesRoute
  SubmitRoute: typeof SubmitRoute
  SubmitQueryRoute: typeof SubmitQueryRoute
  TechnicalSupportRoute: typeof TechnicalSupportRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  VisionMissionRoute: typeof VisionMissionRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accepted-papers': {
      id: '/accepted-papers'
      path: '/accepted-papers'
      fullPath: '/accepted-papers'
      preLoaderRoute: typeof AcceptedPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory-board': {
      id: '/advisory-board'
      path: '/advisory-board'
      fullPath: '/advisory-board'
      preLoaderRoute: typeof AdvisoryBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aims-scope': {
      id: '/aims-scope'
      path: '/aims-scope'
      fullPath: '/aims-scope'
      preLoaderRoute: typeof AimsScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apc': {
      id: '/apc'
      path: '/apc'
      fullPath: '/apc'
      preLoaderRoute: typeof ApcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associate-editors': {
      id: '/associate-editors'
      path: '/associate-editors'
      fullPath: '/associate-editors'
      preLoaderRoute: typeof AssociateEditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-declaration-form': {
      id: '/author-declaration-form'
      path: '/author-declaration-form'
      fullPath: '/author-declaration-form'
      preLoaderRoute: typeof AuthorDeclarationFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-guidelines': {
      id: '/author-guidelines'
      path: '/author-guidelines'
      fullPath: '/author-guidelines'
      preLoaderRoute: typeof AuthorGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copernicus': {
      id: '/copernicus'
      path: '/copernicus'
      fullPath: '/copernicus'
      preLoaderRoute: typeof CopernicusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright-form': {
      id: '/copyright-form'
      path: '/copyright-form'
      fullPath: '/copyright-form'
      preLoaderRoute: typeof CopyrightFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright-license': {
      id: '/copyright-license'
      path: '/copyright-license'
      fullPath: '/copyright-license'
      preLoaderRoute: typeof CopyrightLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright-policy': {
      id: '/copyright-policy'
      path: '/copyright-policy'
      fullPath: '/copyright-policy'
      preLoaderRoute: typeof CopyrightPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crossref': {
      id: '/crossref'
      path: '/crossref'
      fullPath: '/crossref'
      preLoaderRoute: typeof CrossrefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-issue': {
      id: '/current-issue'
      path: '/current-issue'
      fullPath: '/current-issue'
      preLoaderRoute: typeof CurrentIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doi-information': {
      id: '/doi-information'
      path: '/doi-information'
      fullPath: '/doi-information'
      preLoaderRoute: typeof DoiInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks': {
      id: '/ebooks'
      path: '/ebooks'
      fullPath: '/ebooks'
      preLoaderRoute: typeof EbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor-in-chief': {
      id: '/editor-in-chief'
      path: '/editor-in-chief'
      fullPath: '/editor-in-chief'
      preLoaderRoute: typeof EditorInChiefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-board': {
      id: '/editorial-board'
      path: '/editorial-board'
      fullPath: '/editorial-board'
      preLoaderRoute: typeof EditorialBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-office': {
      id: '/editorial-office'
      path: '/editorial-office'
      fullPath: '/editorial-office'
      preLoaderRoute: typeof EditorialOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-scholar': {
      id: '/google-scholar'
      path: '/google-scholar'
      fullPath: '/google-scholar'
      preLoaderRoute: typeof GoogleScholarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-press': {
      id: '/in-press'
      path: '/in-press'
      fullPath: '/in-press'
      preLoaderRoute: typeof InPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexing': {
      id: '/indexing'
      path: '/indexing'
      fullPath: '/indexing'
      preLoaderRoute: typeof IndexingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-reviewer': {
      id: '/join-reviewer'
      path: '/join-reviewer'
      fullPath: '/join-reviewer'
      preLoaderRoute: typeof JoinReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest-articles': {
      id: '/latest-articles'
      path: '/latest-articles'
      fullPath: '/latest-articles'
      preLoaderRoute: typeof LatestArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuscript-template': {
      id: '/manuscript-template'
      path: '/manuscript-template'
      fullPath: '/manuscript-template'
      preLoaderRoute: typeof ManuscriptTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/most-cited': {
      id: '/most-cited'
      path: '/most-cited'
      fullPath: '/most-cited'
      preLoaderRoute: typeof MostCitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/most-viewed': {
      id: '/most-viewed'
      path: '/most-viewed'
      fullPath: '/most-viewed'
      preLoaderRoute: typeof MostViewedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-access-policy': {
      id: '/open-access-policy'
      path: '/open-access-policy'
      fullPath: '/open-access-policy'
      preLoaderRoute: typeof OpenAccessPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peer-review-policy': {
      id: '/peer-review-policy'
      path: '/peer-review-policy'
      fullPath: '/peer-review-policy'
      preLoaderRoute: typeof PeerReviewPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plagiarism-policy': {
      id: '/plagiarism-policy'
      path: '/plagiarism-policy'
      fullPath: '/plagiarism-policy'
      preLoaderRoute: typeof PlagiarismPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publication-ethics': {
      id: '/publication-ethics'
      path: '/publication-ethics'
      fullPath: '/publication-ethics'
      preLoaderRoute: typeof PublicationEthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publication-process': {
      id: '/publication-process'
      path: '/publication-process'
      fullPath: '/publication-process'
      preLoaderRoute: typeof PublicationProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publication-timeline': {
      id: '/publication-timeline'
      path: '/publication-timeline'
      fullPath: '/publication-timeline'
      preLoaderRoute: typeof PublicationTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewers': {
      id: '/reviewers'
      path: '/reviewers'
      fullPath: '/reviewers'
      preLoaderRoute: typeof ReviewersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/road': {
      id: '/road'
      path: '/road'
      fullPath: '/road'
      preLoaderRoute: typeof RoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-issues': {
      id: '/special-issues'
      path: '/special-issues'
      fullPath: '/special-issues'
      preLoaderRoute: typeof SpecialIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission-guidelines': {
      id: '/submission-guidelines'
      path: '/submission-guidelines'
      fullPath: '/submission-guidelines'
      preLoaderRoute: typeof SubmissionGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-query': {
      id: '/submit-query'
      path: '/submit-query'
      fullPath: '/submit-query'
      preLoaderRoute: typeof SubmitQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-support': {
      id: '/technical-support'
      path: '/technical-support'
      fullPath: '/technical-support'
      preLoaderRoute: typeof TechnicalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/archives/issue': {
      id: '/archives/issue'
      path: '/issue'
      fullPath: '/archives/issue'
      preLoaderRoute: typeof ArchivesIssueRouteImport
      parentRoute: typeof ArchivesRoute
    }
    '/archives/volume': {
      id: '/archives/volume'
      path: '/volume'
      fullPath: '/archives/volume'
      preLoaderRoute: typeof ArchivesVolumeRouteImport
      parentRoute: typeof ArchivesRoute
    }
    '/archives/year': {
      id: '/archives/year'
      path: '/year'
      fullPath: '/archives/year'
      preLoaderRoute: typeof ArchivesYearRouteImport
      parentRoute: typeof ArchivesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/conferences/call-for-papers': {
      id: '/conferences/call-for-papers'
      path: '/call-for-papers'
      fullPath: '/conferences/call-for-papers'
      preLoaderRoute: typeof ConferencesCallForPapersRouteImport
      parentRoute: typeof ConferencesRoute
    }
    '/conferences/past': {
      id: '/conferences/past'
      path: '/past'
      fullPath: '/conferences/past'
      preLoaderRoute: typeof ConferencesPastRouteImport
      parentRoute: typeof ConferencesRoute
    }
    '/conferences/proceedings': {
      id: '/conferences/proceedings'
      path: '/proceedings'
      fullPath: '/conferences/proceedings'
      preLoaderRoute: typeof ConferencesProceedingsRouteImport
      parentRoute: typeof ConferencesRoute
    }
    '/ebooks/download': {
      id: '/ebooks/download'
      path: '/download'
      fullPath: '/ebooks/download'
      preLoaderRoute: typeof EbooksDownloadRouteImport
      parentRoute: typeof EbooksRoute
    }
    '/ebooks/submit': {
      id: '/ebooks/submit'
      path: '/submit'
      fullPath: '/ebooks/submit'
      preLoaderRoute: typeof EbooksSubmitRouteImport
      parentRoute: typeof EbooksRoute
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/advertisements': {
      id: '/_authenticated/admin/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AuthenticatedAdminAdvertisementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/board': {
      id: '/_authenticated/admin/board'
      path: '/board'
      fullPath: '/admin/board'
      preLoaderRoute: typeof AuthenticatedAdminBoardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conferences': {
      id: '/_authenticated/admin/conferences'
      path: '/conferences'
      fullPath: '/admin/conferences'
      preLoaderRoute: typeof AuthenticatedAdminConferencesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/doi': {
      id: '/_authenticated/admin/doi'
      path: '/doi'
      fullPath: '/admin/doi'
      preLoaderRoute: typeof AuthenticatedAdminDoiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ebooks': {
      id: '/_authenticated/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AuthenticatedAdminEbooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/impact-factor': {
      id: '/_authenticated/admin/impact-factor'
      path: '/impact-factor'
      fullPath: '/admin/impact-factor'
      preLoaderRoute: typeof AuthenticatedAdminImpactFactorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/issues': {
      id: '/_authenticated/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AuthenticatedAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/advisory-board': {
      id: '/_authenticated/super-admin/advisory-board'
      path: '/advisory-board'
      fullPath: '/super-admin/advisory-board'
      preLoaderRoute: typeof AuthenticatedSuperAdminAdvisoryBoardRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/analytics': {
      id: '/_authenticated/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/animations': {
      id: '/_authenticated/super-admin/animations'
      path: '/animations'
      fullPath: '/super-admin/animations'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnimationsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/announcements': {
      id: '/_authenticated/super-admin/announcements'
      path: '/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/api-keys': {
      id: '/_authenticated/super-admin/api-keys'
      path: '/api-keys'
      fullPath: '/super-admin/api-keys'
      preLoaderRoute: typeof AuthenticatedSuperAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/certificates': {
      id: '/_authenticated/super-admin/certificates'
      path: '/certificates'
      fullPath: '/super-admin/certificates'
      preLoaderRoute: typeof AuthenticatedSuperAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/chief-patrons': {
      id: '/_authenticated/super-admin/chief-patrons'
      path: '/chief-patrons'
      fullPath: '/super-admin/chief-patrons'
      preLoaderRoute: typeof AuthenticatedSuperAdminChiefPatronsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/conferences': {
      id: '/_authenticated/super-admin/conferences'
      path: '/conferences'
      fullPath: '/super-admin/conferences'
      preLoaderRoute: typeof AuthenticatedSuperAdminConferencesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/dashboard': {
      id: '/_authenticated/super-admin/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/deployment': {
      id: '/_authenticated/super-admin/deployment'
      path: '/deployment'
      fullPath: '/super-admin/deployment'
      preLoaderRoute: typeof AuthenticatedSuperAdminDeploymentRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/ebooks': {
      id: '/_authenticated/super-admin/ebooks'
      path: '/ebooks'
      fullPath: '/super-admin/ebooks'
      preLoaderRoute: typeof AuthenticatedSuperAdminEbooksRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/editorial-board': {
      id: '/_authenticated/super-admin/editorial-board'
      path: '/editorial-board'
      fullPath: '/super-admin/editorial-board'
      preLoaderRoute: typeof AuthenticatedSuperAdminEditorialBoardRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/fees': {
      id: '/_authenticated/super-admin/fees'
      path: '/fees'
      fullPath: '/super-admin/fees'
      preLoaderRoute: typeof AuthenticatedSuperAdminFeesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/impact-factors': {
      id: '/_authenticated/super-admin/impact-factors'
      path: '/impact-factors'
      fullPath: '/super-admin/impact-factors'
      preLoaderRoute: typeof AuthenticatedSuperAdminImpactFactorsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/issues': {
      id: '/_authenticated/super-admin/issues'
      path: '/issues'
      fullPath: '/super-admin/issues'
      preLoaderRoute: typeof AuthenticatedSuperAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/papers': {
      id: '/_authenticated/super-admin/papers'
      path: '/papers'
      fullPath: '/super-admin/papers'
      preLoaderRoute: typeof AuthenticatedSuperAdminPapersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/reviewer-board': {
      id: '/_authenticated/super-admin/reviewer-board'
      path: '/reviewer-board'
      fullPath: '/super-admin/reviewer-board'
      preLoaderRoute: typeof AuthenticatedSuperAdminReviewerBoardRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/sites': {
      id: '/_authenticated/super-admin/sites'
      path: '/sites'
      fullPath: '/super-admin/sites'
      preLoaderRoute: typeof AuthenticatedSuperAdminSitesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/team-members': {
      id: '/_authenticated/super-admin/team-members'
      path: '/team-members'
      fullPath: '/super-admin/team-members'
      preLoaderRoute: typeof AuthenticatedSuperAdminTeamMembersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
  }
}

interface AuthenticatedSuperAdminRouteRouteChildren {
  AuthenticatedSuperAdminAdvisoryBoardRoute: typeof AuthenticatedSuperAdminAdvisoryBoardRoute
  AuthenticatedSuperAdminAnalyticsRoute: typeof AuthenticatedSuperAdminAnalyticsRoute
  AuthenticatedSuperAdminAnimationsRoute: typeof AuthenticatedSuperAdminAnimationsRoute
  AuthenticatedSuperAdminAnnouncementsRoute: typeof AuthenticatedSuperAdminAnnouncementsRoute
  AuthenticatedSuperAdminApiKeysRoute: typeof AuthenticatedSuperAdminApiKeysRoute
  AuthenticatedSuperAdminCertificatesRoute: typeof AuthenticatedSuperAdminCertificatesRoute
  AuthenticatedSuperAdminChiefPatronsRoute: typeof AuthenticatedSuperAdminChiefPatronsRoute
  AuthenticatedSuperAdminConferencesRoute: typeof AuthenticatedSuperAdminConferencesRoute
  AuthenticatedSuperAdminDashboardRoute: typeof AuthenticatedSuperAdminDashboardRoute
  AuthenticatedSuperAdminDeploymentRoute: typeof AuthenticatedSuperAdminDeploymentRoute
  AuthenticatedSuperAdminEbooksRoute: typeof AuthenticatedSuperAdminEbooksRoute
  AuthenticatedSuperAdminEditorialBoardRoute: typeof AuthenticatedSuperAdminEditorialBoardRoute
  AuthenticatedSuperAdminFeesRoute: typeof AuthenticatedSuperAdminFeesRoute
  AuthenticatedSuperAdminImpactFactorsRoute: typeof AuthenticatedSuperAdminImpactFactorsRoute
  AuthenticatedSuperAdminIssuesRoute: typeof AuthenticatedSuperAdminIssuesRoute
  AuthenticatedSuperAdminPapersRoute: typeof AuthenticatedSuperAdminPapersRoute
  AuthenticatedSuperAdminReviewerBoardRoute: typeof AuthenticatedSuperAdminReviewerBoardRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminSitesRoute: typeof AuthenticatedSuperAdminSitesRoute
  AuthenticatedSuperAdminTeamMembersRoute: typeof AuthenticatedSuperAdminTeamMembersRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedSuperAdminRouteRouteChildren: AuthenticatedSuperAdminRouteRouteChildren =
  {
    AuthenticatedSuperAdminAdvisoryBoardRoute:
      AuthenticatedSuperAdminAdvisoryBoardRoute,
    AuthenticatedSuperAdminAnalyticsRoute:
      AuthenticatedSuperAdminAnalyticsRoute,
    AuthenticatedSuperAdminAnimationsRoute:
      AuthenticatedSuperAdminAnimationsRoute,
    AuthenticatedSuperAdminAnnouncementsRoute:
      AuthenticatedSuperAdminAnnouncementsRoute,
    AuthenticatedSuperAdminApiKeysRoute: AuthenticatedSuperAdminApiKeysRoute,
    AuthenticatedSuperAdminCertificatesRoute:
      AuthenticatedSuperAdminCertificatesRoute,
    AuthenticatedSuperAdminChiefPatronsRoute:
      AuthenticatedSuperAdminChiefPatronsRoute,
    AuthenticatedSuperAdminConferencesRoute:
      AuthenticatedSuperAdminConferencesRoute,
    AuthenticatedSuperAdminDashboardRoute:
      AuthenticatedSuperAdminDashboardRoute,
    AuthenticatedSuperAdminDeploymentRoute:
      AuthenticatedSuperAdminDeploymentRoute,
    AuthenticatedSuperAdminEbooksRoute: AuthenticatedSuperAdminEbooksRoute,
    AuthenticatedSuperAdminEditorialBoardRoute:
      AuthenticatedSuperAdminEditorialBoardRoute,
    AuthenticatedSuperAdminFeesRoute: AuthenticatedSuperAdminFeesRoute,
    AuthenticatedSuperAdminImpactFactorsRoute:
      AuthenticatedSuperAdminImpactFactorsRoute,
    AuthenticatedSuperAdminIssuesRoute: AuthenticatedSuperAdminIssuesRoute,
    AuthenticatedSuperAdminPapersRoute: AuthenticatedSuperAdminPapersRoute,
    AuthenticatedSuperAdminReviewerBoardRoute:
      AuthenticatedSuperAdminReviewerBoardRoute,
    AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
    AuthenticatedSuperAdminSitesRoute: AuthenticatedSuperAdminSitesRoute,
    AuthenticatedSuperAdminTeamMembersRoute:
      AuthenticatedSuperAdminTeamMembersRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  }

const AuthenticatedSuperAdminRouteRouteWithChildren =
  AuthenticatedSuperAdminRouteRoute._addFileChildren(
    AuthenticatedSuperAdminRouteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdvertisementsRoute: typeof AuthenticatedAdminAdvertisementsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminBoardRoute: typeof AuthenticatedAdminBoardRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminConferencesRoute: typeof AuthenticatedAdminConferencesRoute
  AuthenticatedAdminDoiRoute: typeof AuthenticatedAdminDoiRoute
  AuthenticatedAdminEbooksRoute: typeof AuthenticatedAdminEbooksRoute
  AuthenticatedAdminImpactFactorRoute: typeof AuthenticatedAdminImpactFactorRoute
  AuthenticatedAdminIssuesRoute: typeof AuthenticatedAdminIssuesRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdvertisementsRoute: AuthenticatedAdminAdvertisementsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminBoardRoute: AuthenticatedAdminBoardRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminConferencesRoute: AuthenticatedAdminConferencesRoute,
  AuthenticatedAdminDoiRoute: AuthenticatedAdminDoiRoute,
  AuthenticatedAdminEbooksRoute: AuthenticatedAdminEbooksRoute,
  AuthenticatedAdminImpactFactorRoute: AuthenticatedAdminImpactFactorRoute,
  AuthenticatedAdminIssuesRoute: AuthenticatedAdminIssuesRoute,
  AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSuperAdminRouteRoute: typeof AuthenticatedSuperAdminRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSuperAdminRouteRoute:
    AuthenticatedSuperAdminRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArchivesRouteChildren {
  ArchivesIssueRoute: typeof ArchivesIssueRoute
  ArchivesVolumeRoute: typeof ArchivesVolumeRoute
  ArchivesYearRoute: typeof ArchivesYearRoute
}

const ArchivesRouteChildren: ArchivesRouteChildren = {
  ArchivesIssueRoute: ArchivesIssueRoute,
  ArchivesVolumeRoute: ArchivesVolumeRoute,
  ArchivesYearRoute: ArchivesYearRoute,
}

const ArchivesRouteWithChildren = ArchivesRoute._addFileChildren(
  ArchivesRouteChildren,
)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ConferencesRouteChildren {
  ConferencesCallForPapersRoute: typeof ConferencesCallForPapersRoute
  ConferencesPastRoute: typeof ConferencesPastRoute
  ConferencesProceedingsRoute: typeof ConferencesProceedingsRoute
}

const ConferencesRouteChildren: ConferencesRouteChildren = {
  ConferencesCallForPapersRoute: ConferencesCallForPapersRoute,
  ConferencesPastRoute: ConferencesPastRoute,
  ConferencesProceedingsRoute: ConferencesProceedingsRoute,
}

const ConferencesRouteWithChildren = ConferencesRoute._addFileChildren(
  ConferencesRouteChildren,
)

interface EbooksRouteChildren {
  EbooksDownloadRoute: typeof EbooksDownloadRoute
  EbooksSubmitRoute: typeof EbooksSubmitRoute
}

const EbooksRouteChildren: EbooksRouteChildren = {
  EbooksDownloadRoute: EbooksDownloadRoute,
  EbooksSubmitRoute: EbooksSubmitRoute,
}

const EbooksRouteWithChildren =
  EbooksRoute._addFileChildren(EbooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptedPapersRoute: AcceptedPapersRoute,
  AdvisoryBoardRoute: AdvisoryBoardRoute,
  AimsScopeRoute: AimsScopeRoute,
  ApcRoute: ApcRoute,
  ArchivesRoute: ArchivesRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AssociateEditorsRoute: AssociateEditorsRoute,
  AuthRoute: AuthRoute,
  AuthorDeclarationFormRoute: AuthorDeclarationFormRoute,
  AuthorGuidelinesRoute: AuthorGuidelinesRoute,
  ConferencesRoute: ConferencesRouteWithChildren,
  ContactRoute: ContactRoute,
  CopernicusRoute: CopernicusRoute,
  CopyrightFormRoute: CopyrightFormRoute,
  CopyrightLicenseRoute: CopyrightLicenseRoute,
  CopyrightPolicyRoute: CopyrightPolicyRoute,
  CrossrefRoute: CrossrefRoute,
  CurrentIssueRoute: CurrentIssueRoute,
  DisclaimerRoute: DisclaimerRoute,
  DoiInformationRoute: DoiInformationRoute,
  EbooksRoute: EbooksRouteWithChildren,
  EditorInChiefRoute: EditorInChiefRoute,
  EditorialBoardRoute: EditorialBoardRoute,
  EditorialOfficeRoute: EditorialOfficeRoute,
  FaqsRoute: FaqsRoute,
  GoogleScholarRoute: GoogleScholarRoute,
  InPressRoute: InPressRoute,
  IndexingRoute: IndexingRoute,
  JoinReviewerRoute: JoinReviewerRoute,
  LatestArticlesRoute: LatestArticlesRoute,
  ManuscriptTemplateRoute: ManuscriptTemplateRoute,
  MostCitedRoute: MostCitedRoute,
  MostViewedRoute: MostViewedRoute,
  OpenAccessPolicyRoute: OpenAccessPolicyRoute,
  PeerReviewPolicyRoute: PeerReviewPolicyRoute,
  PlagiarismPolicyRoute: PlagiarismPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  PublicationEthicsRoute: PublicationEthicsRoute,
  PublicationProcessRoute: PublicationProcessRoute,
  PublicationTimelineRoute: PublicationTimelineRoute,
  ReviewersRoute: ReviewersRoute,
  RoadRoute: RoadRoute,
  SpecialIssuesRoute: SpecialIssuesRoute,
  SubmissionGuidelinesRoute: SubmissionGuidelinesRoute,
  SubmitRoute: SubmitRoute,
  SubmitQueryRoute: SubmitQueryRoute,
  TechnicalSupportRoute: TechnicalSupportRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  VisionMissionRoute: VisionMissionRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
